# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build
      run: docker run -d -p 6379:6379 redis:latest

    - name: Build
      run: go build -v ./...

    - name: Test and generate coverage report
      run: |
        go test -timeout=60s -race -v ./cache ./storage ./sync -coverprofile=coverage.out
        go build -race ./...

    - name: Display the coverage report
      run: go tool cover -func=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Install golangci-lint
    #   run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.64.2

    - name: Install golangci-lint (build with current Go)
      run: |
        # Ensure the Go bin directory is on PATH for subsequent steps
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

        # Build and install a specific golangci-lint version using the runner's Go toolchain
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.2

        # sanity check
        golangci-lint --version

    - name: Run golangci-lint
      run: golangci-lint run ./...
